version: "3"
services:
  webserver:
    build:
      context: ./bin/php8.3-apache
    container_name: php8.3-apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./config/apache2/custom.conf:/etc/apache2/mods-enabled/my.conf
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      - ./ssl:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
