version: "3.6"
services:
  webserver:
    image: davidecesarano/docker-compose-lamp
    restart: always
    ports: 
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    links: 
      - mysql
    volumes:
      - ./node:/opt/node
      - ./www:/var/www/html
      - ./config/apache2/custom.conf:/etc/apache2/mods-enabled/my.conf
      - ./config/php/php.ini:/etc/php/7.2/apache2/conf.d/custom.ini 
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./ssl:/etc/letsencrypt
  mysql:
    image: mariadb:latest
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
