version: "3"
services:
  webserver:
    image: davidecesarano/docker-compose-lamp
    container_name: webserver-lamp
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
  mysql:
    image: mariadb:latest
    container_name: mysql-lamp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
