version: "3"
services:
  webserver:
    build: 
      context: ./bin/php/7.2-ubuntu
    container_name: webserver-lamp
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
  mysql:
    build: 
      context: ./bin/mysql
    container_name: mysql-lamp
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes: 
      - ./mysql:/var/lib/mysql